### ISSUE TITLE
Implement spawner sprite and make it change its damaged state

### ISSUE THREAD

**Issue by Ravensherald** [smclaughlan/GWJ52#188]
The spawner sprite is located in Scenes/Region/Spawner_b

**Comment by plexsoup** [comment]
Spawner is now a rift which closes as we hit it with a pickaxe.
I'd like to suggest that we switch the damage to making it more open instead of more closed.

Makes more sense with a picaxe that you'd be making the hole bigger.

To explain away why the creeps stop coming out, we can make the final frame rubble or darker or something.

**Comment by IMAFIREHAZARD** [comment]
State is not ideal, but acceptable. Assets for "destroyed" spawner appears temp. @plexsoup @Ravensherald is more work planned on this? Can we close?

**Comment by plexsoup** [comment]
It'd be easy for me to reverse the order of the sprite frames in code.

So the question is only, should the player be hacking the rifts open or closed with their pickaxe?
I feel like we haven't had that discussion yet.

**Comment by Ravensherald** [comment]
In my opinion it should close, doesnt matter much if you are hitting it with a pickaxe

**Comment by IMAFIREHAZARD** [comment]
Implemented
